server-info:
  # The ID of the main server
  server-id: ''

  ics-channel-listener: ''

  admin-list: ''

emoji:
  monday: '<:1_monday:1336786443061690368>'
  tuesday: '<:2_tuesday:1336786462292836443>'
  wednesday: '<:3_wednesday:1336786470446567464>'
  thursday: '<:4_thursday:1336786480156381315>'
  friday: '<:5_friday:1336786489350164551>'
  saturday: '<:6_saturday:1336786500049698947>'
  sunday: '<:7_sunday:1336786509759643803>'

database:
  host: ''
  port: ''
  user: ''
  password: ''
  database: ''

debug-mode:
  # Useful for testing with a non production database
  enabled: false

  debug-server-id: ''
  debug-channel-id: ''

  debughost: '127.0.0.1'
  debugport: '3306'
  debuguser: 'mainuser'
  debugpassword: 'abcd1234%'
  debugdatabase: 'whitelistTestDatabase'
