server-info:
  # The ID of the main server
  server-id: ''

  admin-user-id: ''

  ics-channel-listener: ''
  silly-video-channel-listener: ''

  schedule-broadcast-channel: ''

  logging-server-id: ''
  logging-channel-id: ''

# Upload these emojis to the dev panel and replace the IDs with the actual IDs
emoji:
  monday: '<:1_monday:1111111111111111111>'
  tuesday: '<:2_tuesday:1111111111111111111>'
  wednesday: '<:3_wednesday:1111111111111111111>'
  thursday: '<:4_thursday:1111111111111111111>'
  friday: '<:5_friday:1111111111111111111>'
  saturday: '<:6_saturday:1111111111111111111>'
  sunday: '<:7_sunday:1111111111111111111>'

database:
  host: ''
  port: ''
  user: ''
  password: ''
  database: ''

webdav:
  enabled: false
  authtype: 'digest'
  url: ''
  username: ''
  password: ''
  filepath: '/calendar.ics'

debug-mode:
  # Useful for testing with a non production database
  enabled: false

  debug-server-id: ''
  debug-channel-id: ''

  debughost: '127.0.0.1'
  debugport: '3306'
  debuguser: 'mainuser'
  debugpassword: 'abcd1234%'
  debugdatabase: 'whitelistTestDatabase'
